In [50]:
#1. Import the NUMPY package under the name np.
import numpy as np


#2. Print the NUMPY version and the configuration.}
print(np.version.version)




#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))


#4. Print a.
print(a)


#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b= np.ones((5,2,3))


#6. Print b.
print(b)


#7. Do a and b have the same size? How do you prove that in Python code?

print(a.size == b.size)


#8. Are you able to add a and b? Why or why not?


#No se pudo porque no tienen la misma "shape"

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = b.reshape(2,3,5)
print(c.shape)

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = np.add(a,c)
#  funcionó.

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print(a)
print(d)



#12. Multiply a and c. Assign the result to e.

e = np.multiply(a,c)

#13. Does e equal to a? Why or why not?

print(a)
print(e)
#Sí fueron iguales

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print('Max={}, Min={}, Mean={}'.format(d_max,d_min,d_mean))

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


f = np.empty([2,3,5])



1.15.4
[[[0.39426536 0.49612643 0.61284829 0.1148676  0.08489896]
  [0.38830282 0.73474702 0.98753263 0.42938691 0.77847781]
  [0.82731678 0.76893865 0.84202493 0.09426616 0.81465434]]

 [[0.08479635 0.66131272 0.54662328 0.06704385 0.9941095 ]
  [0.97957045 0.25756274 0.32545342 0.48175384 0.72159417]
  [0.78686856 0.12165102 0.54535404 0.82999973 0.93981367]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
True
(2, 3, 5)
[[[0.39426536 0.49612643 0.61284829 0.1148676  0.08489896]
  [0.38830282 0.73474702 0.98753263 0.42938691 0.77847781]
  [0.82731678 0.76893865 0.84202493 0.09426616 0.81465434]]

 [[0.08479635 0.66131272 0.54662328 0.06704385 0.9941095 ]
  [0.97957045 0.25756274 0.32545342 0.48175384 0.72159417]
  [0.78686856 0.12165102 0.54535404 0.82999973 0.93981367]]]
[[[1.39426536 1.49612643 1.61284829 1.1148676  1.08489896]
  [1.38830282 1.73474702 1.98753263 1.42938691 1.77847781]
  [1

In [52]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0,0])):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] <= d_min:
                f[i,j,k] = 0
            elif d[i,j,k] > d_mean and d[i,j,k] <= d_max:
                f[i,j,k] = 100


[[[1.39426536 1.49612643 1.61284829 1.1148676  1.08489896]
  [1.38830282 1.73474702 1.98753263 1.42938691 1.77847781]
  [1.82731678 1.76893865 1.84202493 1.09426616 1.81465434]]

 [[1.08479635 1.66131272 1.54662328 1.06704385 1.9941095 ]
  [1.97957045 1.25756274 1.32545342 1.48175384 1.72159417]
  [1.78686856 1.12165102 1.54535404 1.82999973 1.93981367]]]
[[[25. 25. 75. 25. 25.]
  [25. 75. 75. 25. 75.]
  [75. 75. 75. 25. 75.]]

 [[25. 75. 25.  0.  1.]
  [75. 25. 25. 25. 75.]
  [75. 25. 25. 75. 75.]]]


In [53]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)

print(f)
#Sí, obtuvé lo que esperaba.

[[[1.39426536 1.49612643 1.61284829 1.1148676  1.08489896]
  [1.38830282 1.73474702 1.98753263 1.42938691 1.77847781]
  [1.82731678 1.76893865 1.84202493 1.09426616 1.81465434]]

 [[1.08479635 1.66131272 1.54662328 1.06704385 1.9941095 ]
  [1.97957045 1.25756274 1.32545342 1.48175384 1.72159417]
  [1.78686856 1.12165102 1.54535404 1.82999973 1.93981367]]]
[[[25. 25. 75. 25. 25.]
  [25. 75. 75. 25. 75.]
  [75. 75. 75. 25. 75.]]

 [[25. 75. 25.  0.  1.]
  [75. 25. 25. 25. 75.]
  [75. 25. 25. 75. 75.]]]


In [58]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""
g = np.empty([2,3,5], dtype=str)

for i in range(len(d)):
    for j in range(len(d[0])):
        for k in range(len(d[0,0])):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                g[i,j,k] = 'B'
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                g[i,j,k] = 'D'
            elif d[i,j,k] == d_mean:
                g[i,j,k] = 'C'
            elif d[i,j,k] <= d_min:
                g[i,j,k] = 'A'
            elif d[i,j,k] > d_mean and d[i,j,k] <= d_max:
                g[i,j,k] = 'E'
print(g)

[[['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'D' 'D' 'B' 'D']]

 [['B' 'D' 'B' 'A' 'E']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]]


[[['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']
  ['D' 'D' 'D' 'B' 'D']]

 [['B' 'D' 'B' 'A' 'E']
  ['D' 'B' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]]


In [55]:
type('h')

str